### ISSUE TITLE
To-do (better because of checkboxes!)

### ISSUE THREAD

**Issue by Futur3Sn0w** [Futur3Sn0w/Windows10x#2]
# High Priority
- [x] Add tooltips to multibar items
- [x] Add desktop context menu
- [ ] Add multibar context menu
- [x] Make action center area dynamic with icon
- [x] Dark mode
- [x] Wallpaper switcher
- [x] Implement Segoe UI font as website-local rather than system-local
- [x] Fix Launcher (Start Menu) not appearing.
   * Right. But only if it actually works 100% of the time. Check the bug report (#1) for more details.

# Low Priority
- [x] Add a site-wide favicon
- [ ] Mobile device support (through the viewport)

**Comment by Mikhael811** [comment]
Could mobile device support come out?
